### ISSUE TITLE
Using a :token getting repsonse errors

### ISSUE THREAD

**Issue by jakeperry** [ostinelli/apnotic#100]
I have setup the gem to use :token and I am getting a 400 response with {"reason"=>"MissingTopic"}.  Any advice how to set this topic is appreciated.  I know **WHAT** I need to set it to but I am not clear on **HOW** to set it.

**Comment by jakeperry** [comment]
notification.topic = 

was the answer to this problem.

**Comment by lhguerra** [comment]
topic equals what??

**Comment by annaswims** [comment]
notification.topic = [the bundle id]
<img width="1271" alt="Screenshot 2024-05-15 at 3 07 15 PM" src="https://github.com/ostinelli/apnotic/assets/19188/3b01577a-4e3c-49e0-8bab-aacab9d77c28">

**Comment by lhguerra** [comment]
It worked!
