### ISSUE TITLE
Add 'interruption-level' value to the 'apn' dictionary of the notification payload.

### ISSUE THREAD

**Issue by roydaw** [ostinelli/apnotic#105]
### Overview
Starting in iOS 15 you can specify an 'interuption-level' not the 'apn' dictionary to specify how a notification is delivered.

This possible values for 'interruption-level' are:
* Passive (new) - No sound, no vibration, no screen waking, no break through of focus settings.
* Active (default) - Allows sound, vibration, screen waking, no break through of focus settings.
* Time-Sensitive (new) - Allows sound, vibration, screen waking, can break through system controls if allowed.
* Critical - Allows sound, vibration, screen waking, can break through system controls, and bypass ringer switch.

#### Does this feature need to wait until the official iOS 15 Release?
I don't think this feature needs to wait for iOS 15. I would like to work on and test 'time-sensitive' notification ahead of time to be ready for iOS 15.

#### Will this feature break compatibility?
This feature should be none breaking since it is purely additive. 

I think this should be trivial to add and I can put up a PR to make the change. I just want to make sure nobody else is working on it.

**Comment by benubois** [comment]
Done in #106.
