### ISSUE TITLE
Are there any active maintainer of this repo?

### ISSUE THREAD

**Issue by roydaw** [ostinelli/apnotic#107]
It seem like there is little activity from the maintainers of this repo. There are multiple valuable PRs open with no response just waiting to be merged, and the last commit to master is almost a year old. I'm currently targeting a fork so that I can work on supporting features introduced in iOS 15. So what can we do? Can we give more people merge permission? @ostinelli @benubois @stillwaiting @noefroidevaux

**Comment by ostinelli** [comment]
Sure thing. The contributor with most code changes is @benubois: would you be interested in helping out maintaining this repo?

**Comment by ostinelli** [comment]
@benubois has been the person that has done most contributions to the project, and has agreed to see how to help out on this repo. Closing for now.
