### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by stillwaiting** [ostinelli/apnotic#11]
E.g., if I by accident use a dev. certificate while connecting to production, I receive some weird
`HTTP2::Error::ProtocolError: undefined method 'message' for nil:NilClass`

**Comment by stillwaiting** [comment]
Btw I could take this and prepare a PR if I may :)

**Comment by ostinelli** [comment]
Thank you for reporting this. Do you know where this is raised?

Unfortunately we can't do much about errors being `HTTP2::Error::ProtocolError`, as this depends on the [HTTP/2](https://github.com/igrigorik/http-2) gem. See [here](https://github.com/igrigorik/http-2/issues/50) for a similar issue.

**Comment by stillwaiting** [comment]
>Do you know where this is raised?

Seems it comes from [here](https://github.com/igrigorik/http-2/blob/ea7eda3f6cc5585819ef37ef27cd963cdab40b0e/lib/http/2/connection.rb#L430)

So, at [line 659](https://github.com/igrigorik/http-2/blob/ea7eda3f6cc5585819ef37ef27cd963cdab40b0e/lib/http/2/connection.rb#L659) both `msg` and `e` are nils.

```
    654: def connection_error(error = :protocol_error, msg: nil, e: nil)
    655:   binding.pry
    656:   goaway(error) unless @state == :closed || @state == :new
    657: 
    658:   @state, @error = :closed, error
    659:   klass = error.to_s.split('_').map(&:capitalize).join
 => 660:   fail Error.const_get(klass), msg || e.message, e.backtrace || []
    661: end

[3] pry(#<HTTP2::Client>)> klass
=> "ProtocolError"

[4] pry(#<HTTP2::Client>)> Error.const_get(klass)
=> HTTP2::Error::ProtocolError

[5] pry(#<HTTP2::Client>)> msg
=> nil

[6] pry(#<HTTP2::Client>)> e
=> nil

[7] pry(#<HTTP2::Client>)>
```

**Comment by ostinelli** [comment]
That's what I thought. This should not be fixed in Apnotic, but in the underlying [NetHttp2](https://github.com/ostinelli/net-http2) client or [Http/2](https://github.com/igrigorik/http-2/).

Let's see what @igrigorik thinks.

**Comment by igrigorik** [comment]
Yep, looks like something we should fix upstream. @stillwaiting can you open a bug on http/2.. bonus if you have a failing test case :)

**Comment by ostinelli** [comment]
@igrigorik thank you.
@stillwaiting if you open the bug, can you please cross-link it here for future reference?

**Comment by stillwaiting** [comment]
Sure, will do.

**Comment by ostinelli** [comment]
Any news on this?

**Comment by ostinelli** [comment]
No follow ups, closing.
