### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by clarkedb** [ostinelli/apnotic#114]
Is there a plan to support Ruby 3.0.x in a future release of `apnotic`?

**Comment by collimarco** [comment]
We are using it on Ruby 3.0.3.

Have you experienced any problems on that version / newer versions?

**Comment by clarkedb** [comment]
> We are using it on Ruby 3.0.3.
> 
> Have you experienced any problems on that version / newer versions?

No, I just had not been able to verify from the documentation that it would support Ruby 3.x, and my development environment isn't set up to be able to run all of the apnotic code due to issues with actually triggering a pn from that environment. I'm working on getting that working as well though.

I will mark this as closed and submit an issue if I run into an actual problem running it.

**Comment by collimarco** [comment]
In any case someone should add the new ruby version to `.travis.yml` ...

**Comment by clarkedb** [comment]
@collimarco I've submitted a PR to add 3.0 and 3.1. Locally, the tests all pass for both 3.0 and 3.1.
