### ISSUE TITLE
Usage with Sidekiq / Resque example

### ISSUE THREAD

**Issue by gnumarcelo** [ostinelli/apnotic#125]
Hi,
I just have one doubt about the example provided at the [Usage with Sidekiq / Resque](https://github.com/ostinelli/apnotic#with-sidekiq--resque--):
In the example, I can see the error callback being specified:
`connection.on(:error) { |exception| puts "Exception has been raised: #{exception}" }`

But under the [Thread-Safety](https://github.com/ostinelli/apnotic#thread-safety) section, it states:
"If you're using Apnotic with a job manager you should be fine by not specifying this callback."

My question is, if, using it with Sidekiq and I specify the error callback as in the example, it means that once an error happens it will not trigger Sidekiq retry mechanism, is it correct?

ps.: Thanks for making such a great library!!!

**Comment by benubois** [comment]
Hi @gnumarcelo,

The error callback is implemented [here in net-http2](https://github.com/ostinelli/net-http2/blob/2ca17740af00947ab41487255a8ef32a7fa84e5c/lib/net-http2/client.rb#L124-L136). It looks like exceptions are not re-raised, so I think that exceptions raised in the connection will not trigger an automatic retry:

```ruby
def callback_or_raise(exception)
  if callback_events.keys.include?(:error)
    emit(:error, exception)
  else
    raise exception
  end
end
```

You could do something like this to surface the exception for your job, if you also want use an error callback:

```ruby
APNOTIC_POOL = Apnotic::ConnectionPool.new do |connection|
  connection.on(:error) { |exception| 
    puts "Exception has been raised: #{exception}" 
    raise exception
  }
end
```

Thanks!
