### ISSUE TITLE
Have Apnotic::Connection#push return a Future for better concurrency

### ISSUE THREAD

**Issue by mohamedhafez** [ostinelli/apnotic#14]
Taking a look at the connection pool example, after we check out a connection, we have to wait for the full request-response cycle before any other thread can make a request on that connection, which isn't necessary with HTTP/2. I'd suggest `Apnotic::Connection#push` having an option to return a `Future` immediately so we can put the connection back into the pool as soon as possible, and then we can await the `Future` after that. That's the way the [pushy library for Java](https://github.com/relayrides/pushy) does it it seems

**Comment by ostinelli** [comment]
I guess this is mainly linked to the idea of increasing throughput?

The [NetHttp2](https://github.com/ostinelli/net-http2) library used by Apnotic for HTTP/2 calls already allows to perform async calls, so there certainly a way for this. Will think about it.

**Comment by ostinelli** [comment]
@mohamedhafez what would your code look like? Especially in a Resque / Sidekiq environment, you'd still need to have a worker waiting for a response. Hence, even if you were to check the connection back in and use an async call, you'd still have that worker blocked. Can you clarify how you'd envision to do what you're suggesting with a simple code sample?

**Comment by mohamedhafez** [comment]
So I just started using https://github.com/relayrides/pushy from the Java world in my JRuby project, and there's a couple places where the fact that it returns Futures is really helpful

1) Lets say you have a bulk notification you want to send out to 20k users. You can have one thread using one connection send out all 20k async requests, then after those are all sent, resolve the 20k Futures and handle the responses. This makes it take ~30 seconds in my case instead of hours when I was doing the notifications one-by-one waiting for the round trip before moving on to the next notification

2) The other situation is when I have hundreds of threads all trying to use to the same connection. If each thread checks out the connection for the duration of the entire round trip, I'd get way less throughput than if the connection was only checked out for the async request without waiting for the repsonse, and then I put the connection back in the pool so its available for others. The thread at some point blocks on a response its true, but that is only block *that thread*, not everyone waiting to use the connection

**Comment by ostinelli** [comment]
I do not agree with 2. Using connection pools allows to control the input flows. Otherwise, you will easily end up with a system that accepts more than it is able to handle.

However, I understand 1 and I'm ok in having APIs to do async pushes.

How does that sound? :)

**Comment by mohamedhafez** [comment]
Sure, I'm sure that will work. I'm happy with the Pushy library personally, so I'm just giving my two cents.

Regarding 2, you are currently controlling input flows by *drastically* lowering throughput in an unnecessary way: HTTP/2 is meant to support pipelined requests. If input flow control is needed, then perhaps there could be a limit on how many async requests can be made per second, but making it wait for an entire rountrip is way overkill.

**Comment by ostinelli** [comment]
I never said that every request should wait for an entire rountrip, quite the contrary: I agree with your proposal of adding async push, which I think to be a good one,and I thank you for that.

What I'm saying is that I'd like to keep the connections checked out from the pool until all of the async requests in a thread are done. So I'm thinking to address https://github.com/ostinelli/net-http2/issues/3 at the same time. 

With this solution, flow control is simple to control.

**Comment by ostinelli** [comment]
Hi @mohamedhafez, do you have any data on the current implementation? I'd like to propose a change to implement your request but then I'll need it to be backed up by data before it gets to master.

**Comment by mohamedhafez** [comment]
I've never used this library before so I don't have any data, sorry. I just
noticed a huge increase in throughput with the Java Pushy library I
mentioned earlier when doing case #1. I don't have any formal numbers, I
just noticed that messaging all my users went down from hours to approx 30
seconds.

On Tue, Jun 28, 2016 at 2:16 AM, Roberto Ostinelli <notifications@github.com

**Comment by ostinelli** [comment]
Oh I see, so no real Ruby / Rails grounds. Pity.
This change will only benefit either direct Ruby scripts, or Sidekiq / Resque jobs when every single job sends _many_ requests.

Anyway, I will provide this functionality later tonight.

**Comment by ostinelli** [comment]
This is now in. Thank you for your input!
