### ISSUE TITLE
undefined method `prepare_push'

### ISSUE THREAD

**Issue by nextofsearch** [ostinelli/apnotic#18]
Hi,

The sample code in readme for push_async is not working resulting the following error:

`NoMethodError: undefined method `prepare_push' for #<Apnotic::Connection:`

Should I use different commit for push_async?

**Comment by nextofsearch** [comment]
Sorry. My bad. The gem was not updated.

**Comment by ostinelli** [comment]
:)

**Comment by ostinelli** [comment]
@nextofsearch is you end up using this feature, any report you may generate is welcome.

Expect to see major benefits only if you send multiple async pushes in a single job, otherwise you probably won't notice much difference.

**Comment by nextofsearch** [comment]
@ostinelli, we send over hundreds of pushes in a single job and millions of pushes per day. I will post a feedback.

**Comment by ostinelli** [comment]
@nextofsearch  Awesome, thank you. There's an open issue #12 for this valuable feedback :)

**Comment by ostinelli** [comment]
@nextofsearch any news on this? I'm curious about your feedback, especially if we can do something to improve apnotic. :)

**Comment by nextofsearch** [comment]
@ostinelli We haven't deployed it yet since we realized that we have to update the code to handle response codes and to display them in UI. For the test run, it worked great and promising. I will keep you posted if it goes live. Thanks,
