### ISSUE TITLE
response is sometimes nil from connection.push

### ISSUE THREAD

**Issue by danielrhodes** [ostinelli/apnotic#20]
I got an error in my app where it says that the response given back from `connection.push` was nil. Is this expected behavior, and if so what does it mean?

The code where this occurs is as follows:
```ruby
CONNECTION_POOL.with do |connection|
   notification.topic = Rails.application.config.apns_topic
   response = connection.push(notification)
   if response.status == '410' ||
       (response.status == '400' && response.body['reason'] == 'BadDeviceToken')
```

The specific error was `undefined method 'status' for nil:NilClass`

When I looked at connection [here](
https://github.com/ostinelli/apnotic/blob/master/lib/apnotic/connection.rb#L32), it seems the nil is likely coming upstream from the HTTP2 library.

Any help is appreciated!

**Comment by ostinelli** [comment]
From the README:

> ##### Blocking calls
>
> * **push(notification, timeout: 30)** → **`Apnotic::Response` or `nil`**
>
> Sends a notification. Returns `nil` in case a timeout occurs.

Does this help?

**Comment by danielrhodes** [comment]
Yes. It helps by teaching me to read the docs more carefully. :-P

**Comment by ostinelli** [comment]
^^_
