### ISSUE TITLE
production readiness

### ISSUE THREAD

**Issue by ebalassanian** [ostinelli/apnotic#21]
Hi, I have looking at your gem and am considering using it in a production environment for a rails app. My app sends out large numbers of APNs to client devices to manage background updates to client data. I was originally considering using sidekiq and rolling my own APNs manager. Based on my very cursory review, it looks like I can use Apnotic with async push support instead.  I was wondering if you feel this gem is ready for production use for the scenario I'm considering.

**Comment by ostinelli** [comment]
We use it in production with Sidekiq. I know of various installations, one of which is of @benubois (maybe he can also give some insights).

**Comment by nextofsearch** [comment]
Hi, I was about to use it in production with Sidekiq but bumped into a segmentation fault due to Couchbase gem, which does not seem to be fixed any time soon. Please be aware if you use Couchbase. What a bummer. :( Of course, nothing wrong with apnotic.

**Comment by ebalassanian** [comment]
Thanks for the feedback. I'm curious why you use it with sidekiq as opposed to leveraging the async calls in the library.

**Comment by ebalassanian** [comment]
p.s. I have the gem integrated now and async notifications are up and running. So far so good. Thanks for the effort on the gem. It was a big time saver. I'll let you know as I continue in the development effort if you are interested in my results.

**Comment by ostinelli** [comment]
> Thanks for the feedback. I'm curious why you use it with sidekiq as opposed to leveraging the async calls in the library.

Sidekiq manages retries.

**Comment by ostinelli** [comment]
> I'll let you know as I continue in the development effort if you are interested in my results.

Absolutely. Please do keep me informed.

**Comment by ostinelli** [comment]
Closing this question. @ebalassanian, if you have any feedback please reply in #12, thank you!
