### ISSUE TITLE
Custom payload containing {'aps' => ... } does not work

### ISSUE THREAD

**Issue by schmidp** [ostinelli/apnotic#24]
n.alert = "hi"      
puts n.body
{"aps":{"alert":"hi"}}

n.custom_payload = payload_apns
puts n.body
{"aps":{"alert":"hi"},"aps":{"alert":"Hello","sound":"default"}}

"aps" is now twice in the JSON

**Comment by benubois** [comment]
Hi @schmidp,

I'm not sure what your `payload_apns` method/variable does, but if you take a look at [`to_hash`](https://github.com/ostinelli/apnotic/blob/9856e291c861036788ac89d81086a1f5eed97c80/lib/apnotic/notification.rb#L34) you can see that `custom_payload` does get merged in correctly.

You need to make sure you are using the same key. So to replace `aps` entirely, you'll be wanting to overload the `:aps` key. For example:

```ruby
notification = Apnotic::Notification.new('token')
notification.alert = {
  title: "title"
}
puts notification.body
#=> {"aps":{"alert":{"title":"title"}}}

notification.custom_payload = {aps: {alert: {title: "new_title"}}}
puts notification.body
#=> {"aps":{"alert":{"title":"new_title"}}}

```

**Comment by schmidp** [comment]
@benubois The problem is not using symbols in the custom_payload but strings:

notification = Apnotic::Notification.new('token')
notification.alert = {
  title: "title"
}
puts notification.body
{"aps":{"alert":{"title":"title"}}}

notification.custom_payload = {"aps" => {"alert" => {"title" => "new_title"}}}
puts notification.body
{"aps":{"alert":{"title":"title"}},"aps":{"alert":{"title":"new_title"}}}

The only difference is:
  notification.custom_payload = {"aps" => {"alert" => {"title" => "new_title"}}}
vs
  notification.custom_payload = {aps: {alert: {title: "new_title"}}}

I'm not saying I cannot use symbols, it's just something that trips you up while using it.

**Comment by ostinelli** [comment]
Hello @schmidp, this is a good catch but at the same time: why would any developer try to add a custom payload in the `aps` element? I don't like to enforce too much rigidity, so if a developer were to do that, wouldn't they probably know that they are entering uncharted territory?
