### ISSUE TITLE
NoMethodError(undefined method `ok?' for nil:NilClass)

### ISSUE THREAD

**Issue by mat** [ostinelli/apnotic#27]
From time to time 

```ruby
response = connection.push(notification)
```

is returning a `nil` response resulting in an

```
NoMethodError(undefined method `ok?' for nil:NilClass)
```

error. I've no clue so far why this is happening. It looks to me that NetHTTP2 might be swallowing an error here that could be helpful for debugging.

I yet have to see if there is any logging/additional information inside apnotic or NetHTTP2 that could help me debug this, cause I'd love to know the underlying cause.

**Comment by ostinelli** [comment]
From the README:

> ##### Blocking calls
>
> * **push(notification, timeout: 30)** → **`Apnotic::Response` or `nil`**
>
> Sends a notification. Returns `nil` in case a timeout occurs.


See #20.

**Comment by mat** [comment]
D'oh. Thanks and sorry for the noise.

**Comment by ostinelli** [comment]
No worries :) BTW @mat, if you have usage statistics please feel free to contribute to #12.
