### ISSUE TITLE
Add support for the new JWT-based authentication.

### ISSUE THREAD

**Issue by idyll** [ostinelli/apnotic#31]
Apple is now allowing developers to use a JWT token instead of a cert:
  https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html

Go implementation here:
  https://github.com/RobotsAndPencils/buford/issues/63

Interesting things about this new approach:
1. you need the topic. 
2. you can push to all apps in the org. (hence why you need the topic).
3. you can only open 1 stream until you send a push. at that point apple will advertise a new max # of streams to you.

**Comment by ostinelli** [comment]
For reference, there has already been a first try from @benubois in https://github.com/ostinelli/apnotic/pull/28.

I haven't had the time to check implementations yet.

**Comment by idyll** [comment]
This needs changes to the HTTP/2 lib to support. I think a starting # of streams and then the ability to listen to Apples requests to modify those streams.
