### ISSUE TITLE
Update documentation with with caution over memory leak.

### ISSUE THREAD

**Issue by idyll** [ostinelli/apnotic#37]
I was having an issue where my sidekiq workers were leaking memory when sending notifications using apnotic. 

The source of the leak is indicated in the code below. It's related to the use of a connection pool when sending notifications.

```ruby
  def perform(token)
    # build the notification outside of the connection block.
    # if you build the notification inside the block memory associated with it is never released.
    notification       = Apnotic::Notification.new(token)
    notification.alert = "Hello from Apnotic!"

    APNOTIC_POOL.with do |connection|
      # making a notification inside the block will leak the object.
      #  notification       = Apnotic::Notification.new(token)
      #  notification.alert = "Hello from Apnotic!"

      response = connection.push(notification)
      raise "Timeout sending a push notification" unless response

      if response.status == '410' ||
        (response.status == '400' && response.body['reason'] == 'BadDeviceToken')
        Device.find_by(token: token).destroy
      end
    end
  end
```

We send such a large volume of notifications that we'd end up using over 1GB of memory every 12 hours which would eventually run us out of memory.

The above example is the synchronous code, but the same is true with async. You need to build the notification outside of the pool or you leak.

**Comment by ostinelli** [comment]
Hello @idyll,
Before doing anything I'd like to have an understanding of what is happening.

Some time ago @jcs opened an issue (https://github.com/ostinelli/net-http2/issues/7) regarding a potential leak in the underlying [Http2 library](https://github.com/igrigorik/http-2), but I have seen no follow up. Maybe @igrigorik can comment?

**Comment by igrigorik** [comment]
I'm not aware of any leaks in http-2 lib, but that doesn't mean they're not there.. A profile would go a long way here.

**Comment by ostinelli** [comment]
@igrigorik FYI after I receive a `:close` event on a stream, if I force listeners on the stream [emitter](https://github.com/igrigorik/http-2/blob/v0.8.2/lib/http/2/emitter.rb) to be nil:

```ruby
h2_stream.instance_variable_set(:@listeners, nil)
``` 

Then there's no more leak. Any ideas?

**Comment by idyll** [comment]
Since this is a production system, it's not super easy/convenient to profile. But I am totally willing to do it. @igrigorik can you tell me what you'd like me to capture if I profile this. I only want to do it once.

@ostinelli I assure you, there's a leak if you make that object in the connection block. Pulling it out of the block fixes it. I have tested the code both ways - ran in production overnight - with only that change. Sending around 35K notifications per hour.

I do suspect there's likely an unrelated leak in the http-2 lib based on the memory usage that I am seeing.

**Comment by ostinelli** [comment]
I may have found the culprit and a solution for this, described in https://github.com/ostinelli/net-http2/issues/7.

**Comment by idyll** [comment]
I don't think it's related to multi streams. If I force the notifications through one at a time I still get the leak. I think it's related to the connection pool block. (But I could be wrong.)

**Comment by idyll** [comment]
I will fork the http-2 gem and try the fix in ostinelli/net-http2#7. I am really curious to see what the result of that is.

**Comment by danielrhodes** [comment]
I believe I'm having a similar issue. Except it looks like `fsevent_watch` has been spawned a bunch of times. Is apnotic or the http2 library forking anywhere?

**Comment by danielrhodes** [comment]
@ostinelli Any idea on this? I have to remove this gem if I can't find a solution. Even in development it is eating up all available resources in my system.

**Comment by ostinelli** [comment]
@danielrhodes what kind of idea should I have? I have traced down the memory leak to an external gem and if you follow the references you'll see that it's currently being evaluated and should be released this week. :)

More info here: https://github.com/igrigorik/http-2/issues/73

**Comment by ostinelli** [comment]
@danielrhodes if you are referring to something else, please open another issue and detail what you are experiencing so we can investigate. Thanks.

**Comment by ostinelli** [comment]
Closed as solved from source.
