### ISSUE TITLE
Receiving SocketError: Socket was remotely closed

### ISSUE THREAD

**Issue by noctivityinc** [ostinelli/apnotic#41]
We just implemented Apnotic and are receiving `SocketError: Socket was remotely closed` when we try to send a notification.  How do we debug?

**Comment by ostinelli** [comment]
There's nothing to debug: this means that the socket was remotely closed. Apnotic raises an error by design, from the README:

> In case that errors are encountered, Apnotic will raise the error and repair the underlying connection, but it will not retry the requests that have failed. This is by design, so that the job manager (Sidekiq, Resque,...) can retry the job that failed. For this reason, it is recommended to use a queue engine that will retry unsuccessful pushes.
