### ISSUE TITLE
Rails app crashing when using integer value for header

### ISSUE THREAD

**Issue by printercu** [ostinelli/apnotic#42]
Hi!

I had `notifiaction.apns_collapse_id = order.id` and app was crashing with `HTTP2::Error::ProtocolError (HTTP2::Error::ProtocolError)` and no backtrace. Sometimes exception was rescued with message `undefined method 'bytesize' for 2:Fixnum.` But sometimes it wasn't even rescued, app just crashed.

Changing to `order.id.to_s` fixed this.

**Comment by ostinelli** [comment]
Thank you for your report. This needs a patch [here](https://github.com/ostinelli/apnotic/blob/1.0.1/lib/apnotic/request.rb#L20), will do ASAP.

**Comment by printercu** [comment]
Is it possible to fix http-2 lib, so it would not crash ruby process if any other possible header is not string?

**Comment by ostinelli** [comment]
Yes, that is a possibility, thanks for the suggestion. I am unsure whether the underlying http-2 gem requires al headers to be string though. Will need to check that out.

**Comment by ostinelli** [comment]
This is now fixed in https://github.com/ostinelli/net-http2/commit/e2c15d3f2fe79b0b56655b199c120e7491881aca.
