### ISSUE TITLE
action-loc-key to customize button

### ISSUE THREAD

**Issue by augustosamame** [ostinelli/apnotic#44]
Hi. According to the Apple Docs: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW5

I can use an action-loc-key field to customize the texts shown in action buttons in push notifications.
I've been trying this:

```
notification       = Apnotic::Notification.new(token)
        notification.alert = {
          body: alert,
          action-loc-key: 'Accept'
          }

```
but action-loc-key is an invalid key in Ruby.
Any ideas?

**Comment by benubois** [comment]
Try the old "rocket" syntax:

```ruby
"action-loc-key" => "Accept"
```

**Comment by ostinelli** [comment]
Indeed, thank you @benubois.
