### ISSUE TITLE
After send about 10k APNS, sidekiq lost respose.

### ISSUE THREAD

**Issue by smoothdvd** [ostinelli/apnotic#48]
Connection reset by peer
/home/alex/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock'
/home/alex/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
/home/alex/apps/dskb-web/shared/bundle/ruby/2.2.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:133:in `block in socket_loop'
/home/alex/apps/dskb-web/shared/bundle/ruby/2.2.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:130:in `loop'
/home/alex/apps/dskb-web/shared/bundle/ruby/2.2.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:130:in `socket_loop'
/home/alex/apps/dskb-web/shared/bundle/ruby/2.2.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:102:in `block (2 levels) in ensure_open'

is this like [socket loop thread abort_on_exception (was: Thread Safety) #4](https://github.com/ostinelli/net-http2/issues/4)

How to resolve it?

```
APNOTIC_POOL = Apnotic::ConnectionPool.new(
    {
      cert_path: Rails.root.join('config', 'apns-production.pem'),
      cert_pass: ''
    }, size: 5
  )

def perform(post_id, device_id, message)
    APNOTIC_POOL.with do |connection|
      notifications = Redis::HashKey.new(
        "notifications:#{post_id}", marshal: true
      )
      object = JSON.parse(message)
      noti = Apnotic::Notification.new(object['token'])
      noti.alert = object['alert']
      noti.badge = 0
      noti.sound = 'default'
      noti.topic = 'xxx'
      noti.custom_payload = object['custom_data']
      response = connection.push(noti)

      raise 'Timeout sending a push notification' unless response

      if response.status == '410' ||
         (response.status == '400' &&
          response.body['reason'] == 'BadDeviceToken')
        notifications.delete(device_id.to_s)
        # TODO: SHOULD REMOVE THE DEVICE FROM NotificationDevice
      end
    end
  end
```

**Comment by ujihisa** [comment]
Not sure if it shares same root cause or irrelevant, but here I also got a similar error that has killed my application for 3 times in the past.

```
Socket was remotely closed
/home/applications/xxx/shared/vendor/bundle/ruby/2.3.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:122:in `callback_or_raise'
/home/applications/xxx/shared/vendor/bundle/ruby/2.3.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:107:in `rescue in block (2 levels) in ensure_open'
/home/applications/xxx/shared/vendor/bundle/ruby/2.3.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:101:in `block (2 levels) in ensure_open'
```

My sidekiq worker is almost identical to the README and the code by @smoothdvd; sending a single message synchronously within `perform` method of a sidekiq worker.

The underlying library net-http2 issue should be already fixed, and the version both @smoothdvd and I are using are the latest one though.

**Comment by ostinelli** [comment]
From the README:

> In case that errors are encountered, Apnotic will raise the error and repair the underlying connection, but it will not retry the requests that have failed. This is by design, so that the job manager (Sidekiq, Resque,...) can retry the job that failed. For this reason, it is recommended to use a queue engine that will retry unsuccessful pushes.

Also:

> Errors in the underlying socket loop thread will be raised in the main thread at unexpected execution times, unless you specify the :error callback on the Connection. If you're using Apnotic with a job manager you should be fine by not specifying this callback.

You can therefore specify a different behavior if this is not the one you're looking for.

See also https://github.com/ostinelli/apnotic/issues/45 and https://github.com/ostinelli/apnotic/issues/41.

**Comment by ujihisa** [comment]
I'm not sure if I'm understanding your statement, but can you explain what's the different behaviour that I can choose? The error kills the sidekiq process, not a single `perform` task, so I wonder if it matters to specify or not specify :error callbacks.

**Comment by ostinelli** [comment]
Sidekiq spawns a ne thread for every job. When an error like this is raised, only that thread is killed, not the whole Sidekiq. Hence, the job queue will restart the failed job with a new thread.

Again, from the README:

> * **on(event, &block)**
>
> Allows to set a callback for the connection. The only available event is `:error`, which allows to set a callback when an error is raised at socket level, hence in the underlying socket thread.
>
```ruby
connection.on(:error) { |exception| puts "Exception has been raised: #{exception}" }
```
>
> If the `:error` callback is not set, the underlying socket thread may raise an error in the main thread at unexpected execution times. 

So that's the different behavior that you can specify if you desire.
Hope this helps.

**Comment by ujihisa** [comment]
Awesome, thx! For some reason that `on(:error)` part was only for the async push, even though it clearly said that it was for `connection`. I'll try that and observe if it eventually crashes or not!

**Comment by ujihisa** [comment]
Good news: for the past 9 days, the issue didn't reproduce. You are the life saver!

I recommend updating the sidekiq example of apnotic README to include the `on` to handle exceptions in the other thread. If you want I can make a pullreq later.

Current example in the latest README file:

```ruby
require 'apnotic'

class MyWorker
  include Sidekiq::Worker

  sidekiq_options queue: :push_notifications

  APNOTIC_POOL = Apnotic::ConnectionPool.new({
    cert_path: Rails.root.join("config", "certs", "apns_certificate.pem"),
    cert_pass: "mypass"
  }, size: 5)

  def perform(token)
    APNOTIC_POOL.with do |connection|
      notification       = Apnotic::Notification.new(token)
      notification.alert = "Hello from Apnotic!"

      response = connection.push(notification)
      raise "Timeout sending a push notification" unless response

      if response.status == '410' ||
        (response.status == '400' && response.body['reason'] == 'BadDeviceToken')
        Device.find_by(token: token).destroy
      end
    end
  end
end
```

**Comment by smoothdvd** [comment]
@ujihisa can you share your error handle code?

**Comment by ujihisa** [comment]
@smoothdvd almost literally same as ostinelli's, except for using sidekiq's `logger.error` instead of `puts`. It's at the very beginning of the `with` block.

**Comment by smoothdvd** [comment]
@ujihisa Like this ?
```
def perform(post_id, device_id, message)
  APNOTIC_POOL.with do |connection|
    connection.on(:error) do |exception|
      logger.error "Exception has been raised: #{exception}"
    end
  end
end
```

**Comment by ujihisa** [comment]
@smoothdvd yes

**Comment by ostinelli** [comment]
What is the issue if an error is raised in the sidekiq process when a `Socket was remotely closed`?

**Comment by ujihisa** [comment]
The issue is that not only the specific worker job but the entire sidekiq UNIX process dies.

**Comment by ostinelli** [comment]
This is where my experience is different: I use this code in 3 different production environments and sidekiq is always up. Do you host your sidekiq, are you on Heroku, other?

**Comment by smoothdvd** [comment]
@ujihisa Finally my sidekiq worker has worked about 10 days without crash!

**Comment by aalsanad** [comment]
@ostinelli @smoothdvd 
My experience is similar to what @ujihisa explained, however swallowing the exception on error is not desirable because we want notifications sent! if we raise an exception from within the method or comment the bulk, the entire sidekiq process dies! this happened much more frequently since we updated to the latest version of apnotic.

I hope you guys can help us with this.

**Comment by smoothdvd** [comment]
@aalsanad catch error except only lead sidekiq job to failed or retry. Please check your sidekiq worker code first.

**Comment by moofkit** [comment]
@ujihisa I have callback for this but it still falling.
There is a code inside worker:
```
      def send_notifications(notifications)
        connection_pool.with do |connection|
          notifications.each do |notification|
            push = connection.prepare_push(notification)

            push.on(:error) do |exception|
              logger.error "Exception has been raised: #{exception}"
            end

            push.on(:response) do |response|
              if response.status == "410" || (response.status == "400" && response.body["reason"] == "BadDeviceToken")
                bad_notification = notifications.find { |n| n.apns_id == response.headers["apns-id"] }
                Device.where(push_token: bad_notification.token).update_all(push_token: nil)
              elsif response.status != "200"
                logger.info("[push_notifications ios] #{response.body['reason']}")
              end
            end
            connection.push_async(push)
          end
          connection.join
        end
      end
```
what's wrong is here? Maybe you can help me?

**Comment by moofkit** [comment]
ahhh I see, its obviously should be a connection callback.
so this is right code example:
```ruby
      def send_notifications(notifications)
        connection_pool.with do |connection|
          connection.on(:error) do |exception|
            logger.error "Exception has been raised: #{exception}"
          end

          notifications.each do |notification|
            push = connection.prepare_push(notification)
            push.on(:response) do |response|
              if response.status == "410" || (response.status == "400" && response.body["reason"] == "BadDeviceToken")
                bad_notification = notifications.find { |n| n.apns_id == response.headers["apns-id"] }
                Device.where(push_token: bad_notification.token).update_all(push_token: nil)
              elsif response.status != "200"
                logger.info("[push_notifications ios] #{response.body['reason']}")
              end
            end
            connection.push_async(push)
          end
          connection.join
        end
      end
```

**Comment by moofkit** [comment]
oh my, this drive me crazy.
@ostinelli I have same issue that described here. The code example of worker that sends pushes is described in this [PR](https://github.com/ostinelli/apnotic/pull/65).
As i suppose the reason why sidekiq process is died is this one https://github.com/ostinelli/net-http2/blob/master/lib/net-http2/client.rb#L122
with this flag any exception raised within any child thread will kill main thread too.
We have other opportunity and just catch this error and log error or do nothing as described here https://github.com/ostinelli/apnotic/issues/48#issuecomment-309952880 but in this case worker just stuck until whole sidekiq process restart.
There are an example of log that we've received 
![](https://user-images.githubusercontent.com/3938172/39168877-98c376fa-47a6-11e8-9a81-348415707624.png)

Can you explain please how to manage async pushes correctly within workers? It will be very helpful if you left some comments for this [PR](https://github.com/ostinelli/apnotic/pull/65)

**Comment by smoothdvd** [comment]
@moofkit Work with Sidekiq, you should just use sync method,  connection.push(notification).

**Comment by alsutton** [comment]
I think this might be causing a memory leak because each time the pooled connection is re-used the error handler would be re-added meaning that the list of handlers would grow and grow until the connection is killed.

Have I missed something?
