### ISSUE TITLE
Add support for proxy parameters in Connection.new()

### ISSUE THREAD

**Issue by dineshnamburi** [ostinelli/apnotic#76]
This is an enhancement request.

net-http2 gem supports proxy parameters (proxy host, port, user, password).
So, it would be great if we can pass these parameters in Apnotic::Connection.new() which in turn creates net-http2 client with these proxy params.
It will be useful for Apnotic gem users, working behind a corporate proxy.

Thanks!

**Comment by n-miyo** [comment]
Hi @ostinelli, thank you for creating good gem!

Do you have a plan to create code for solving this issue? I created a small PR #78 for supporting proxy settings.  Could you check it if you have time.
Thank you.
