### ISSUE TITLE
Update for breaking change in iOS 13

### ISSUE THREAD

**Issue by dylanbromby** [ostinelli/apnotic#86]
Whether or not https://github.com/ostinelli/apnotic/pull/85 is accepted, this gem needs to be updated to support the `apns-push-type` header requirement for iOS 13, currently in its 8th beta. It would be great if @ostinelli and/or other authors could make this a priority so it can be tested in advance of iOS 13's public release.

This is a great library - perhaps consider allowing the addition of any header key/value pair rather than abstracting into fixed method parameters in the future? That might eliminate the need for updates in the event Apple requires additional header values in the future.

Reference:

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

**Comment by ostinelli** [comment]
What are you suggesting here? You are referring to iOS13 which is already discussed in #85, then adding the concept of loosening header check. Is the latter what you are bringing forward? If so can you please clarify your intents and adapt the title, thanks.

**Comment by dylanbromby** [comment]
The issue really was twofold: 1) there had been no movement regarding iOS 13 and #85 so my primary intent was to help move that along, and 2) the suggestion of allowing header values to be set as params. But since the primary concern was updating for iOS 13, I don't think the issue title needs to be updated. Regarding the suggestion of passing header values in as params, it was really just a passing thought and doesn't detract from our usage.
