### ISSUE TITLE
connection.join does not take any parameters like the documentation suggests. 

### ISSUE THREAD

**Issue by zrice57** [ostinelli/apnotic#96]
The `push_async` docs give an example with a join timeout:
```
# wait for all requests to be completed
connection.join(timeout: 5)
```

However, that method takes no parameters:
```
def join
    @client.join
end
```

I think this should look like 
```
def join(timeout: nil)
    @client.join(timeout)
end
```

**Comment by ostinelli** [comment]
You are looking at the documentation in master, this hasn't yet been implemented.

**Comment by zrice57** [comment]
Oh my mistake, thank you

**Comment by ostinelli** [comment]
Implemented and pushed.

**Comment by patriciojofre** [comment]
thank you, now it works perfectly
